[package]
name = "switchedule"
description="Nintendo Switch game release schedule"
version = "0.1.0"
authors = ["duan <wddwyss@gmail.com>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.2"
tera = "0.10"
lazy_static = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
